### ISSUE TITLE
(Optional) Add ability for a user to unlike an item (DELETE /item/iid/liked/user) 

### ISSUE THREAD

**Issue by raycoll** [CS130-spring2015-barter/backend-api#54]

**Comment by raycoll** [comment]
- To "unlike" an item we should delete the row in the liked table and ADD a row in the seen item table

**Comment by MatteoVH** [comment]
I don't think we should allow this functionality. Are there any practical uses?

**Comment by raycoll** [comment]
Well a user probably would want to remove an item from their list of "liked" items. For example, they might be done negotiating and unable to come to an agreement. I made it optional because I doubt client is going to get this far
